'use client';

import { useState } from 'react';
import { ArrowRight, ArrowUpRight, Database, Fingerprint, Shield } from 'lucide-react';
import { byId } from '@/config/instruments';
import { loanRiskMeter } from '@/domain/loan-risk';
import { stockIdentityForEarn, type StockPositionRow } from '@/domain/portfolio';
import type { EarnPosition, Holding, Loan, Portfolio, UnmodeledLoan, WalletAsset } from '@/domain/types';
import type { ReadContext } from '@/domain/guards';
import { amount, date, percent, short, time, usdAmount } from '@/components/format';
import { IdentityIcon } from '@/components/asset-logo';
import { LoanRiskMeter } from '@/components/loan-risk-meter';
import { Modal } from '@/components/modal';

export function AssetIcon({ id, label, logoUrl, kind = 'asset' }: { id: string; label?: string; logoUrl?: string | null; kind?: 'asset'|'company'|'fund' }) {
  return <IdentityIcon id={id} label={label} logoUrl={logoUrl} kind={kind}/>;
}

const locationLabel = { wallet: 'Wallet', posted: 'Posted collateral', earn: 'Earn' } as const;

export function StockPositionsTable({ rows, onMarket }: { rows: StockPositionRow[]; onMarket?: (mint: string) => void }) {
  if (!rows.length) return <div className="no-results">No verified stock or ETF positions were found in this section.</div>;
  return <div className="table-scroll"><table className="holdings-table stock-position-table"><thead><tr><th>Asset</th><th>Location</th><th className="numeric">Quantity</th><th className="numeric">Reference value</th></tr></thead><tbody>{rows.map(row=><tr key={`${row.location}:${row.id}`}><td>{onMarket ? <button className="asset-cell portfolio-market-link" onClick={() => onMarket(row.mint)} aria-label={`Open ${row.symbol} public market details`}><AssetIcon id={row.symbol} label={row.name} logoUrl={row.logoUrl}/><div><strong>{row.symbol}</strong><span>{row.name} · {row.assetClass === 'etf' ? 'ETF' : 'Stock'}</span></div><ArrowRight size={14}/></button> : <div className="asset-cell"><AssetIcon id={row.symbol} label={row.name} logoUrl={row.logoUrl}/><div><strong>{row.symbol}</strong><span>{row.name} · {row.assetClass === 'etf' ? 'ETF' : 'Stock'}</span></div></div>}</td><td><span className={`location ${row.location}`}><span/>{locationLabel[row.location]}</span></td><td className="numeric"><strong>{amount(row.amount,2,9)}</strong><span className="cell-sub">display units</span></td><td className="numeric"><strong>{usdAmount(row.referenceValueUsd)}</strong><span className="cell-sub">{row.referenceValueUsd === null ? 'price unavailable' : row.valueValidity === 'stale' ? 'dated reference · stale' : 'reference USD'}</span></td></tr>)}</tbody></table></div>;
}

export function HoldingsTable({ holdings, walletAssets = [] }: { holdings: Holding[]; walletAssets?: WalletAsset[] }) {
  if (!holdings.length && !walletAssets.length) return <div className="no-results">No assets were returned for this section.</div>;
  return <div className="table-scroll"><table className="holdings-table"><thead><tr><th>Asset</th><th>Location</th><th className="numeric">Quantity</th><th className="numeric">Reference value</th></tr></thead><tbody>{holdings.map(h=><tr key={h.id}><td><div className="asset-cell"><AssetIcon id={h.instrumentId} label={byId[h.instrumentId]?.name}/><div><strong>{h.instrumentId}</strong><span>{byId[h.instrumentId]?.name || h.mintState.mint}</span></div></div></td><td><span className={`location ${h.scope}`}><span/>{h.scope==='wallet'?'Wallet':'Posted collateral'}</span></td><td className="numeric"><strong>{amount(h.displayAmount, h.instrumentId==='USDC'?2:4,9)}</strong><span className="cell-sub">{h.instrumentId==='USDC'?'USDC':'display units'}</span></td><td className="numeric"><strong>{usdAmount(h.referenceValue?.amount)}</strong><span className="cell-sub">{h.referenceValue? h.source.kind==='sample'?'simulated reference':h.referenceValue.source.validity==='stale'?'dated reference · stale':'reference USD':'price unavailable'}</span></td></tr>)}{walletAssets.map(asset=><tr key={asset.id}><td><div className="asset-cell"><AssetIcon id={asset.symbol} label={asset.name} logoUrl={asset.logoUrl}/><div><strong>{asset.symbol || 'Unknown token'}</strong><span>{asset.name || short(asset.mint)}</span></div></div></td><td><span className="location wallet"><span/>Wallet</span></td><td className="numeric"><strong>{amount(asset.amount,2,9)}</strong><span className="cell-sub">{asset.amount === null ? 'amount unavailable' : asset.amountConvention==='scaled-ui'?'scaled display units':asset.amountConvention==='interest-bearing'?'interest-adjusted units':'token units'}</span></td><td className="numeric"><strong>{usdAmount(asset.referenceValue?.amount)}</strong><span className="cell-sub">{asset.referenceValue?.source.validity==='stale'?'dated reference · stale':asset.referenceValue?'reference USD':'price unavailable'}</span></td></tr>)}</tbody></table></div>;
}

export function EarnPositions({ positions, heading = 'Jupiter Earn', description = 'Deposited underlying assets and current projected variable yield.', overview = false }: { positions: EarnPosition[]; heading?: string; description?: string; overview?: boolean }) {
  if (!positions.length) return overview ? null : <section className="portfolio-section"><div className="section-heading"><div><h2>{heading}<span className="count">0</span></h2><p>{description}</p></div><span className="jupiter-label"><span/>Jupiter Lend · read only</span></div><div className="panel portfolio-empty"><Database size={19}/><span><strong>No Earn positions found</strong><small>No deposited Jupiter Earn underlying assets were returned.</small></span></div></section>;
  return <section className={overview ? 'overview-earn-section' : 'portfolio-section'}><div className="section-heading"><div><h2>{heading}<span className="count">{positions.length}</span></h2><p>{description}</p></div><span className="jupiter-label"><span/>Jupiter Lend · read only</span></div><div className="earn-grid">{positions.map(position=>{
    const instrument = stockIdentityForEarn(position);
    const card = <><div><AssetIcon id={instrument?.id || position.symbol} label={instrument?.name || position.name} logoUrl={position.logoUrl}/><span><strong>{instrument?.symbol || position.symbol}</strong><small>{instrument ? `${instrument.name} · ${instrument.issuer}` : position.name}</small></span></div><div><span>Deposited</span><strong>{amount(position.amount,2,9)} {position.symbol}</strong><small>{usdAmount(position.referenceValue?.amount)} reference value</small></div><div><span>Projected APY</span><strong>{percent(position.apy,2)}</strong><small>Variable rate</small></div><div className="earn-source"><span className="location earn"><span/>Earn</span><small>{position.source.validity === 'stale' ? 'Stale · ' : ''}{date(position.source.observedAt)} · {time(position.source.retrievedAt)}</small></div></>;
    return overview ? <article className="panel earn-card" key={position.id}>{card}</article> : <a className="panel earn-card" key={position.id} href={position.link} target="_blank" rel="noreferrer">{card}<ArrowUpRight size={17}/></a>;
  })}</div></section>;
}

export function IndexedPositions({ data }: { data: Portfolio }) {
  const positions = data.indexedPositions || [];
  if (!positions.length) return <div className="panel portfolio-empty"><Database size={19}/><span><strong>No indexed comparison positions</strong><small>Jupiter Portfolio returned no additional protocol records.</small></span></div>;
  return <div className="panel indexed-positions"><div className="indexed-title"><Database size={15}/>Jupiter indexed protocol view<span>Indexed-only · {positions.length} position{positions.length===1?'':'s'}</span></div><p>Independent Jupiter Portfolio values for coverage comparison. They are never added again to PositionLayer totals.</p><div>{positions.map(position=><div className="indexed-row" key={position.id}><span><strong>{position.name || position.label}</strong><small>{position.platformId} · {position.type} · Indexed-only</small></span><strong>{usdAmount(position.valueUsd)}</strong>{position.link&&<a href={position.link} target="_blank" rel="noreferrer" aria-label={`Open ${position.name || position.label}`}><ArrowUpRight size={15}/></a>}</div>)}</div></div>;
}

function UnmodeledLoanRow({ loan }: { loan: UnmodeledLoan }) {
  return <div className="panel unmodeled-loan"><div className="unmodeled-identity"><span className="paired-icons"><AssetIcon id={loan.collateralSymbol} label={loan.collateralName} logoUrl={loan.collateralLogoUrl}/><AssetIcon id={loan.debtSymbol} label={loan.debtName} logoUrl={loan.debtLogoUrl}/></span><span><strong>{loan.collateralSymbol} / {loan.debtSymbol}</strong><small>Vault {loan.vaultId} · Position #{loan.positionId}</small></span></div><div><span>Supplied</span><strong>{amount(loan.collateralAmount,2,9)} {loan.collateralSymbol}</strong></div><div><span>Borrowed</span><strong>{amount(loan.debtAmount,2,9)} {loan.debtSymbol}</strong></div><p>{loan.reason}</p><a href={loan.link} target="_blank" rel="noreferrer" aria-label={`Open Jupiter position ${loan.positionId}`}><ArrowUpRight size={17}/></a></div>;
}

export function LoanCard({ portfolio, loan, context, onDetails, onStress }: { portfolio:Portfolio; loan: Loan; context:ReadContext; onDetails: () => void; onStress:()=>void }) {
  const risk=loanRiskMeter(portfolio,loan,context);
  return <article className={`panel loan-card risk-loan-card risk-${risk.state}`}><div className="loan-card-top"><div className="loan-identity"><div className="paired-icons"><AssetIcon id={loan.collateralInstrumentId}/><AssetIcon id={loan.debtInstrumentId}/></div><div><h3>{loan.collateralInstrumentId} / {loan.debtInstrumentId}</h3><span>Vault {loan.vaultId} · {loan.source.kind==='sample'?'Sample position':`Position #${loan.positionId}`}</span></div></div><div className="loan-stat"><span>Protocol collateral</span><strong>{loan.collateralValue ? `${amount(loan.collateralValue.amount,2,9)} ${loan.debtInstrumentId}` : 'Unavailable'}</strong><small>Liquidation-oracle basis · represented once above as posted collateral</small></div><div className="loan-stat"><span>Accrued debt</span><strong>{amount(loan.debtUnscaled,2,9)} {loan.debtInstrumentId}</strong><small>Protocol accounting</small></div></div><LoanRiskMeter risk={risk}/><div className="loan-card-actions"><span>Observed {loan.source.kind==='sample'?'in fixture':`${Math.max(0,Math.floor((context.now-Date.parse(loan.source.observedAt))/1000))}s ago`}</span><button className="text-button" onClick={onDetails}>Technical details</button><button className="button" onClick={onStress}>Stress this loan<ArrowRight size={15}/></button></div></article>;
}

function LoanDetails({ loan }: { loan: Loan }) {
  return <div className="source-details"><p className="notice">{loan.source.kind==='sample'?'Simulated values. This is not an onchain position.':'Read-only onchain position. No transaction or signature capability is present.'}</p><dl><dt>Collateral accounting amount</dt><dd>{loan.collateralAccountingRaw} / 10⁹</dd><dt>Debt accounting amount</dt><dd>{loan.debtAccountingRaw} / 10⁹ USDC</dd><dt>Maximum borrowing LTV (B)</dt><dd>{percent(loan.maxBorrowLtv)}</dd><dt>Liquidation threshold (T)</dt><dd>{percent(loan.liquidationThreshold)}</dd><dt>Liquidation penalty</dt><dd>{percent(loan.liquidationPenalty)}</dd><dt>Observation</dt><dd>{date(loan.source.observedAt)} · {time(loan.source.observedAt)}</dd><dt>Slot range</dt><dd>{loan.source.slot===null?'Not supplied':`${loan.source.slot}–${loan.source.endSlot}`}</dd></dl><p>currentLtv = accrued debt / protocol collateral. Boundary used = currentLtv / T. Decline buffer = 1 − currentLtv / T. Health factor = T / currentLtv.</p><p>Protocol values are in USDC using the Jupiter Lend liquidation-oracle basis. They remain separate from reference USD exposure and hypothetical scenarios.</p>{loan.source.url&&<a href={loan.source.url} target="_blank" rel="noreferrer">View position source<ArrowUpRight size={13}/></a>}</div>;
}

export function BorrowPositions({ data, context, onStress, compactLoanId = null }: { data: Portfolio; context: ReadContext; onStress: (loanId:string)=>void; compactLoanId?: string | null }) {
  const [selectedLoanId,setSelectedLoanId] = useState<string | null>(null);
  const loans = compactLoanId ? data.loans.filter(loan => loan.id === compactLoanId) : data.loans;
  const selectedLoan = data.loans.find(loan => loan.id === selectedLoanId);
  return <>{loans.length ? loans.map(loan=><LoanCard key={loan.id} portfolio={data} loan={loan} context={context} onDetails={()=>setSelectedLoanId(loan.id)} onStress={()=>onStress(loan.id)}/>) : <div className="panel empty-loans"><Shield size={22}/><div><h3>{data.loanRead==='ready'?'No modeled loans found':'Loan data is unavailable'}</h3><p>{data.loanRead==='ready'?'No supported Jupiter borrow position is present in this snapshot.':'Check the coverage notes or read a specific position.'}</p></div></div>}{!compactLoanId && (data.unmodeledLoans || []).map(loan=><UnmodeledLoanRow loan={loan} key={loan.id}/>)}{selectedLoan&&<Modal title="Loan source details" onClose={()=>setSelectedLoanId(null)}><LoanDetails loan={selectedLoan}/></Modal>}</>;
}

export function ExcludedAssets({ data }: { data: Portfolio }) {
  const untrusted = (data.walletAssets || []).filter(asset => asset.verification !== 'verified');
  const count = untrusted.length + data.unsupported.length;
  if (!count) return <div className="panel portfolio-empty"><Fingerprint size={19}/><span><strong>No excluded assets</strong><small>No unverified, suspicious, receipt, or unsupported balance was returned.</small></span></div>;
  return <div className="panel excluded-assets"><div className="excluded-heading"><Fingerprint size={16}/><strong>{count} excluded record{count===1?'':'s'}</strong><span>Never included in totals</span></div>{untrusted.map(asset=><div className="excluded-row" key={asset.id}><div><AssetIcon id={asset.symbol} label={asset.name} logoUrl={asset.logoUrl}/><span><strong>{asset.symbol || 'Unknown token'}</strong><small>{short(asset.mint)} · {asset.verification}</small></span></div><p>{asset.verification === 'suspicious' ? 'Suspicious token metadata; excluded.' : 'Issuer or token identity is unverified; excluded.'}</p></div>)}{data.unsupported.map(asset=><div className="excluded-row" key={asset.mint}><div><AssetIcon id={asset.mint} label="Excluded mint"/><span><strong>{short(asset.mint)}</strong><small>{asset.accountCount} account{asset.accountCount===1?'':'s'} · Excluded</small></span></div><p>{asset.reason}</p></div>)}</div>;
}
